# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Staticcheck is a go vet on steroids
    - unused        # Check for unused constants, variables, functions and types
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Check for misspelled words
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - gosec         # Security checker

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow  # Can be too noisy

  gofmt:
    simplify: true

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Allow embedding in webfs package
    - path: webfs/webfs\.go
      text: "embed"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
